[phases.setup]
nixPkgs = ["python39", "chromium", "wget", "unzip"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install chromium"
]

[phases.build]
cmds = ["echo 'Build completed'"]
